MLB.eyepiecesJson = {
	'eyepieces': [
		{manufacturer: 'APM', type: 'Ultra Flat Field', focalLengthmm: '8', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'APM', type: 'Ultra Flat Field', focalLengthmm: '10', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'APM', type: 'Ultra Flat Field', focalLengthmm: '12', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'APM', type: 'Ultra Flat Field', focalLengthmm: '15', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'APM', type: 'Ultra Flat Field', focalLengthmm: '18', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'APM', type: 'Ultra Flat Field', focalLengthmm: '19', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'APM', type: 'Ultra Flat Field', focalLengthmm: '24', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'APM', type: 'Ultra Flat Field', focalLengthmm: '30', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'APM', type: 'Ultra Wide', focalLengthmm: '30', fieldStopmm: '', apparentField: '80'},
		{manufacturer: 'APM', type: 'HDC Extreme Wide Angle', focalLengthmm: '20', fieldStopmm: '', apparentField: '100'},
		{manufacturer: 'APM', type: 'HDC Extreme Wide Angle', focalLengthmm: '13', fieldStopmm: '', apparentField: '100'},
		{manufacturer: 'Astro-Tech', type: 'AF Series', focalLengthmm: '3.7', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Astro-Tech', type: 'High Grade Plossl', focalLengthmm: '4', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Astro-Tech', type: 'High Grade Plossl', focalLengthmm: '6', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Astro-Tech', type: 'High Grade Plossl', focalLengthmm: '12.5', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Astro-Tech', type: 'High Grade Plossl', focalLengthmm: '17', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Astro-Tech', type: 'High Grade Plossl', focalLengthmm: '20', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Astro-Tech', type: 'Paradigm Dual ED', focalLengthmm: '5', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Astro-Tech', type: 'Paradigm Dual ED', focalLengthmm: '8', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Astro-Tech', type: 'Paradigm Dual ED', focalLengthmm: '12', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Astro-Tech', type: 'Paradigm Dual ED', focalLengthmm: '15', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Astro-Tech', type: 'Paradigm Dual ED', focalLengthmm: '18', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Astro-Tech', type: 'Paradigm Dual ED', focalLengthmm: '25', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Astro-Tech', type: 'Value Line Plossl', focalLengthmm: '4', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Astro-Tech', type: 'Value Line Plossl', focalLengthmm: '6', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Astro-Tech', type: 'Value Line Plossl', focalLengthmm: '12.5', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Astro-Tech', type: 'Value Line Plossl', focalLengthmm: '15', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Astro-Tech', type: 'Value Line Plossl', focalLengthmm: '20', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Astro-Tech', type: 'Value Line Plossl', focalLengthmm: '25', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Astro-Tech', type: 'Value Line Plossl', focalLengthmm: '32', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Astro-Tech', type: 'Value Line Plossl', focalLengthmm: '40', fieldStopmm: '', apparentField: '40'},
		{manufacturer: 'Baader Planetarium', type: 'Classic Ortho', focalLengthmm: '6', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Baader Planetarium', type: 'Classic Ortho', focalLengthmm: '10', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Baader Planetarium', type: 'Classic Ortho', focalLengthmm: '18', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Baader Planetarium', type: 'Classic Plossl', focalLengthmm: '32', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Baader Planetarium', type: 'Hyperion', focalLengthmm: '5', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Baader Planetarium', type: 'Hyperion', focalLengthmm: '8', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Baader Planetarium', type: 'Hyperion', focalLengthmm: '10', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Baader Planetarium', type: 'Hyperion', focalLengthmm: '13', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Baader Planetarium', type: 'Hyperion', focalLengthmm: '17', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Baader Planetarium', type: 'Hyperion', focalLengthmm: '21', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Baader Planetarium', type: 'Hyperion', focalLengthmm: '24', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Baader Planetarium', type: 'Hyperion', focalLengthmm: '31', fieldStopmm: '', apparentField: '72'},
		{manufacturer: 'Baader Planetarium', type: 'Hyperion', focalLengthmm: '36', fieldStopmm: '', apparentField: '72'},
		{manufacturer: 'Baader Planetarium', type: 'Morpheus', focalLengthmm: '4.5', fieldStopmm: '', apparentField: '76'},
		{manufacturer: 'Baader Planetarium', type: 'Morpheus', focalLengthmm: '6.5', fieldStopmm: '', apparentField: '76'},
		{manufacturer: 'Baader Planetarium', type: 'Morpheus', focalLengthmm: '9', fieldStopmm: '', apparentField: '76'},
		{manufacturer: 'Baader Planetarium', type: 'Morpheus', focalLengthmm: '12.5', fieldStopmm: '', apparentField: '76'},
		{manufacturer: 'Baader Planetarium', type: 'Morpheus', focalLengthmm: '14', fieldStopmm: '', apparentField: '76'},
		{manufacturer: 'Baader Planetarium', type: 'Morpheus', focalLengthmm: '17.5', fieldStopmm: '', apparentField: '76'},
		{manufacturer: 'Celestron', type: 'Axiom', focalLengthmm: '15', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Celestron', type: 'Axiom', focalLengthmm: '19', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Celestron', type: 'Axiom', focalLengthmm: '23', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Celestron', type: 'Axiom', focalLengthmm: '34', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Celestron', type: 'Axiom', focalLengthmm: '40', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Celestron', type: 'Axiom', focalLengthmm: '50', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Celestron', type: 'E-Lux', focalLengthmm: '6', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Celestron', type: 'E-Lux', focalLengthmm: '10', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Celestron', type: 'E-Lux', focalLengthmm: '25', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Celestron', type: 'E-Lux', focalLengthmm: '40', fieldStopmm: '', apparentField: '43'},
		{manufacturer: 'Celestron', type: 'E-Lux-2"', focalLengthmm: '26', fieldStopmm: '', apparentField: '56'},
		{manufacturer: 'Celestron', type: 'E-Lux-2"', focalLengthmm: '32', fieldStopmm: '', apparentField: '56'},
		{manufacturer: 'Celestron', type: 'E-Lux-2"', focalLengthmm: '40', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Celestron', type: 'Omni', focalLengthmm: '4', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Celestron', type: 'Omni', focalLengthmm: '6', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Celestron', type: 'Omni', focalLengthmm: '9', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Celestron', type: 'Omni', focalLengthmm: '12.5', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Celestron', type: 'Omni', focalLengthmm: '15', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Celestron', type: 'Omni', focalLengthmm: '20', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Celestron', type: 'Omni', focalLengthmm: '25', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Celestron', type: 'Omni', focalLengthmm: '32', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Celestron', type: 'Omni', focalLengthmm: '40', fieldStopmm: '', apparentField: '43'},
		{manufacturer: 'Celestron', type: 'Ultima', focalLengthmm: '5', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Celestron', type: 'Ultima', focalLengthmm: '7.5', fieldStopmm: '', apparentField: '51'},
		{manufacturer: 'Celestron', type: 'Ultima', focalLengthmm: '10', fieldStopmm: '', apparentField: '51'},
		{manufacturer: 'Celestron', type: 'Ultima', focalLengthmm: '12.5', fieldStopmm: '', apparentField: '51'},
		{manufacturer: 'Celestron', type: 'Ultima', focalLengthmm: '18', fieldStopmm: '', apparentField: '51'},
		{manufacturer: 'Celestron', type: 'Ultima', focalLengthmm: '30', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Celestron', type: 'Ultima', focalLengthmm: '35', fieldStopmm: '', apparentField: '49'},
		{manufacturer: 'Celestron', type: 'Ultima', focalLengthmm: '42', fieldStopmm: '', apparentField: '36'},
		{manufacturer: 'Celestron', type: 'X-Cel', focalLengthmm: '2.3', fieldStopmm: '', apparentField: '55'}, 
		{manufacturer: 'Celestron', type: 'X-Cel', focalLengthmm: '5', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Celestron', type: 'X-Cel', focalLengthmm: '8', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Celestron', type: 'X-Cel', focalLengthmm: '10', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Celestron', type: 'X-Cel', focalLengthmm: '12.5', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Celestron', type: 'X-Cel', focalLengthmm: '18', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Celestron', type: 'X-Cel', focalLengthmm: '21', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Celestron', type: 'X-Cel', focalLengthmm: '25', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Clave', type: 'Plossl', focalLengthmm: '3', fieldStopmm: '2.7', apparentField: '48'},
		{manufacturer: 'Clave', type: 'Plossl', focalLengthmm: '4', fieldStopmm: '3.6', apparentField: '48'},
		{manufacturer: 'Clave', type: 'Plossl', focalLengthmm: '5', fieldStopmm: '4.4', apparentField: '48'},
		{manufacturer: 'Clave', type: 'Plossl', focalLengthmm: '6', fieldStopmm: '5.3', apparentField: '48'},
		{manufacturer: 'Clave', type: 'Plossl', focalLengthmm: '8', fieldStopmm: '7.1', apparentField: '48'},
		{manufacturer: 'Clave', type: 'Plossl', focalLengthmm: '10', fieldStopmm: '8.9', apparentField: '48'},
		{manufacturer: 'Clave', type: 'Plossl', focalLengthmm: '12', fieldStopmm: '10.7', apparentField: '48'},
		{manufacturer: 'Clave', type: 'Plossl', focalLengthmm: '16', fieldStopmm: '14.2', apparentField: '48'},
		{manufacturer: 'Clave', type: 'Plossl', focalLengthmm: '20', fieldStopmm: '17.8', apparentField: '48'},
		{manufacturer: 'Clave', type: 'Plossl', focalLengthmm: '25', fieldStopmm: '22.3', apparentField: '48'},
		{manufacturer: 'Clave', type: 'Plossl', focalLengthmm: '30', fieldStopmm: '26.8', apparentField: '48'},
		{manufacturer: 'Clave', type: 'Plossl', focalLengthmm: '35', fieldStopmm: '26.8', apparentField: '42'},
		{manufacturer: 'Edmund Scientific', type: 'RKE', focalLengthmm: '8', fieldStopmm: '6.6', apparentField: '45'},
		{manufacturer: 'Edmund Scientific', type: 'RKE', focalLengthmm: '12', fieldStopmm: '9.7', apparentField: '45'},
		{manufacturer: 'Edmund Scientific', type: 'RKE', focalLengthmm: '15', fieldStopmm: '11.9', apparentField: '45'},
		{manufacturer: 'Edmund Scientific', type: 'RKE', focalLengthmm: '21', fieldStopmm: '17.3', apparentField: '45'},
		{manufacturer: 'Edmund Scientific', type: 'RKE', focalLengthmm: '28', fieldStopmm: '23.3', apparentField: '45'},
		{manufacturer: 'Explore Scientific', type: '120 series', focalLengthmm: '9', fieldStopmm: '15.7', apparentField: '120'},
		{manufacturer: 'Explore Scientific', type: '100 series', focalLengthmm: '30', fieldStopmm: '52.2', apparentField: '100'}, // 3" diameter barrel 
		{manufacturer: 'Explore Scientific', type: '100 series', focalLengthmm: '25', fieldStopmm: '41', apparentField: '100'},
		{manufacturer: 'Explore Scientific', type: '100 series', focalLengthmm: '20', fieldStopmm: '34.8', apparentField: '100'},
		{manufacturer: 'Explore Scientific', type: '100 series', focalLengthmm: '14', fieldStopmm: '24.4', apparentField: '100'},
		{manufacturer: 'Explore Scientific', type: '100 series', focalLengthmm: '9', fieldStopmm: '15.7', apparentField: '100'},
		{manufacturer: 'Explore Scientific', type: '100 series', focalLengthmm: '5.5', fieldStopmm: '9.6', apparentField: '100'},
		{manufacturer: 'Explore Scientific', type: '92 LE Series', focalLengthmm: '17', fieldStopmm: '27.5', apparentField: '92'},
		{manufacturer: 'Explore Scientific', type: '92 LE Series', focalLengthmm: '12', fieldStopmm: '19.6', apparentField: '92'},
		{manufacturer: 'Explore Scientific', type: '82 series', focalLengthmm: '30', fieldStopmm: '43', apparentField: '82'},
		{manufacturer: 'Explore Scientific', type: '82 series', focalLengthmm: '24', fieldStopmm: '33.5', apparentField: '82'},
		{manufacturer: 'Explore Scientific', type: '82 series', focalLengthmm: '18', fieldStopmm: '25.3', apparentField: '82'},
		{manufacturer: 'Explore Scientific', type: '82 series', focalLengthmm: '14', fieldStopmm: '18.9', apparentField: '82'},
		{manufacturer: 'Explore Scientific', type: '82 series', focalLengthmm: '11', fieldStopmm: '15.9', apparentField: '82'},
		{manufacturer: 'Explore Scientific', type: '82 series', focalLengthmm: '8.8', fieldStopmm: '12.4', apparentField: '82'},
		{manufacturer: 'Explore Scientific', type: '82 series', focalLengthmm: '6.7', fieldStopmm: '9.5', apparentField: '82'},
		{manufacturer: 'Explore Scientific', type: '82 series', focalLengthmm: '4.7', fieldStopmm: '6.9', apparentField: '82'},
		{manufacturer: 'Explore Scientific', type: '68 series', focalLengthmm: '40', fieldStopmm: '52.2', apparentField: '68'},
		{manufacturer: 'Explore Scientific', type: '68 series', focalLengthmm: '34', fieldStopmm: '38.6', apparentField: '68'},
		{manufacturer: 'Explore Scientific', type: '68 series', focalLengthmm: '28', fieldStopmm: '31.8', apparentField: '68'},
		{manufacturer: 'Explore Scientific', type: '68 series', focalLengthmm: '24', fieldStopmm: '27.2', apparentField: '68'},
		{manufacturer: 'Explore Scientific', type: '68 series', focalLengthmm: '20', fieldStopmm: '22.8', apparentField: '68'},
		{manufacturer: 'Explore Scientific', type: '68 series', focalLengthmm: '16', fieldStopmm: '18.2', apparentField: '68'},
		{manufacturer: 'Fujiyama', type: 'HD-OR', focalLengthmm: '4', fieldStopmm: '2.6', apparentField: '42'},
		{manufacturer: 'Fujiyama', type: 'HD-OR', focalLengthmm: '5', fieldStopmm: '3.4', apparentField: '42'},
		{manufacturer: 'Fujiyama', type: 'HD-OR', focalLengthmm: '6', fieldStopmm: '4.2', apparentField: '42'},
		{manufacturer: 'Fujiyama', type: 'HD-OR', focalLengthmm: '7', fieldStopmm: '4.8', apparentField: '42'},
		{manufacturer: 'Fujiyama', type: 'HD-OR', focalLengthmm: '9', fieldStopmm: '6.3', apparentField: '42'},
		{manufacturer: 'Fujiyama', type: 'HD-OR', focalLengthmm: '4', fieldStopmm: '9.2', apparentField: '42'},
		{manufacturer: 'Fujiyama', type: 'HD-OR', focalLengthmm: '4', fieldStopmm: '12.5', apparentField: '42'},
		{manufacturer: 'Fujiyama', type: 'HD-OR', focalLengthmm: '4', fieldStopmm: '17.4', apparentField: '42'},
		{manufacturer: 'Masuyama', type: '46 deg AFOV', focalLengthmm: '32', fieldStopmm: '', apparentField: '46'},
		{manufacturer: 'Masuyama', type: '46 deg AFOV', focalLengthmm: '45', fieldStopmm: '', apparentField: '46'},
		{manufacturer: 'Masuyama', type: '46 deg AFOV', focalLengthmm: '50', fieldStopmm: '', apparentField: '46'},
		{manufacturer: 'Masuyama', type: '46 deg AFOV', focalLengthmm: '60', fieldStopmm: '', apparentField: '46'},
		{manufacturer: 'Masuyama', type: '53 deg AFOV', focalLengthmm: '45', fieldStopmm: '', apparentField: '53'},
		{manufacturer: 'Masuyama', type: '53 deg AFOV', focalLengthmm: '50', fieldStopmm: '', apparentField: '53'},
		{manufacturer: 'Masuyama', type: '85 deg AFOV', focalLengthmm: '10', fieldStopmm: '', apparentField: '85'},
		{manufacturer: 'Masuyama', type: '85 deg AFOV', focalLengthmm: '16', fieldStopmm: '', apparentField: '85'},
		{manufacturer: 'Masuyama', type: '85 deg AFOV', focalLengthmm: '20', fieldStopmm: '', apparentField: '85'},
		{manufacturer: 'Masuyama', type: '85 deg AFOV', focalLengthmm: '26', fieldStopmm: '', apparentField: '85'},
		{manufacturer: 'Masuyama', type: '85 deg AFOV', focalLengthmm: '32', fieldStopmm: '', apparentField: '85'},
		{manufacturer: 'Masuyama', type: '85 deg AFOV', focalLengthmm: '20', fieldStopmm: '', apparentField: '85'},
		{manufacturer: 'Masuyama', type: '3 inch barrel', focalLengthmm: '80', fieldStopmm: '70', apparentField: '52'},
		{manufacturer: 'Lunt', type: 'HDC', focalLengthmm: '3.5', fieldStopmm: '', apparentField: '110'},
		{manufacturer: 'Lunt', type: 'HDC', focalLengthmm: '5', fieldStopmm: '', apparentField: '110'},
		{manufacturer: 'Lunt', type: 'HDC', focalLengthmm: '9', fieldStopmm: '', apparentField: '100'},
		{manufacturer: 'Lunt', type: 'HDC', focalLengthmm: '13', fieldStopmm: '', apparentField: '100'},
		{manufacturer: 'Lunt', type: 'HDC', focalLengthmm: '20', fieldStopmm: '', apparentField: '100'},
		{manufacturer: 'Meade', type: 'Series 4000 Plossl', focalLengthmm: '6.4', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Meade', type: 'Series 4000 Plossl', focalLengthmm: '9.7', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Meade', type: 'Series 4000 Plossl', focalLengthmm: '12.4', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Meade', type: 'Series 4000 Plossl', focalLengthmm: '15', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Meade', type: 'Series 4000 Plossl', focalLengthmm: '20', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Meade', type: 'Series 4000 Plossl', focalLengthmm: '26', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Meade', type: 'Series 4000 Plossl', focalLengthmm: '32', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Meade', type: 'Series 4000 Plossl', focalLengthmm: '40', fieldStopmm: '', apparentField: '44'},
		{manufacturer: 'Meade', type: 'Series 4000 Plossl', focalLengthmm: '56', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Meade', type: 'Series 5000 Plossl', focalLengthmm: '5.5', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Meade', type: 'Series 5000 Plossl', focalLengthmm: '9', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Meade', type: 'Series 5000 Plossl', focalLengthmm: '14', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Meade', type: 'Series 5000 Plossl', focalLengthmm: '20', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Meade', type: 'Series 5000 Plossl', focalLengthmm: '26', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Meade', type: 'Series 5000 Plossl', focalLengthmm: '32', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Meade', type: 'Series 5000 Plossl', focalLengthmm: '40', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Meade', type: 'Series 5000 SWA', focalLengthmm: '16', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Meade', type: 'Series 5000 SWA', focalLengthmm: '20', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Meade', type: 'Series 5000 SWA', focalLengthmm: '24', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Meade', type: 'Series 5000 SWA', focalLengthmm: '28', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Meade', type: 'Series 5000 SWA', focalLengthmm: '34', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Meade', type: 'Series 5000 SWA', focalLengthmm: '40', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Meade', type: 'Series 5000 UWA', focalLengthmm: '4.7', fieldStopmm: '', apparentField: ' 82'},
		{manufacturer: 'Meade', type: 'Series 5000 UWA', focalLengthmm: '6.7', fieldStopmm: '', apparentField: ' 82'},
		{manufacturer: 'Meade', type: 'Series 5000 UWA', focalLengthmm: '8.8', fieldStopmm: '', apparentField: ' 82'},
		{manufacturer: 'Meade', type: 'Series 5000 UWA', focalLengthmm: '14', fieldStopmm: '', apparentField: ' 82'},
		{manufacturer: 'Meade', type: 'Series 5000 UWA', focalLengthmm: '18', fieldStopmm: '', apparentField: ' 82'},
		{manufacturer: 'Meade', type: 'Series 5000 UWA', focalLengthmm: '24', fieldStopmm: '', apparentField: ' 82'},
		{manufacturer: 'Meade', type: 'Series 5000 UWA', focalLengthmm: '30', fieldStopmm: '', apparentField: ' 82'},
		{manufacturer: 'Meade', type: 'QX Wide Angle', focalLengthmm: '15', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Meade', type: 'QX Wide Angle', focalLengthmm: '20', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Meade', type: 'QX Wide Angle', focalLengthmm: '26', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Meade', type: 'QX Wide Angle', focalLengthmm: '36', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Nikon', type: 'NAV EiC', focalLengthmm: '10', fieldStopmm: '', apparentField: '102'},
		{manufacturer: 'Nikon', type: 'NAV SW', focalLengthmm: '5', fieldStopmm: '', apparentField: '72'},
		{manufacturer: 'Nikon', type: 'NAV SW', focalLengthmm: '7', fieldStopmm: '', apparentField: '72'},
		{manufacturer: 'Nikon', type: 'NAV SW', focalLengthmm: '10', fieldStopmm: '', apparentField: '72'},
		{manufacturer: 'Nikon', type: 'NAV SW', focalLengthmm: '14', fieldStopmm: '', apparentField: '72'},
		{manufacturer: 'Nikon', type: 'NAV SW', focalLengthmm: '17.5', fieldStopmm: '', apparentField: '72'},
		{manufacturer: 'Nikon', type: 'NAV EiC', focalLengthmm: '10', fieldStopmm: '17.9', apparentField: '102'},
		{manufacturer: 'Nikon', type: 'NAV', focalLengthmm: '12.5', fieldStopmm: '22.5', apparentField: '102'},
		{manufacturer: 'Nikon', type: 'NAV EiC', focalLengthmm: '14', fieldStopmm: '24.6', apparentField: '102'},
		{manufacturer: 'Nikon', type: 'NAV', focalLengthmm: '17', fieldStopmm: '30.1', apparentField: '102'},
		{manufacturer: 'Olivon', type: 'FMC', focalLengthmm: '3.5', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Olivon', type: 'FMC', focalLengthmm: '5', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Olivon', type: 'FMC', focalLengthmm: '8', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Olivon', type: 'FMC', focalLengthmm: '13', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Olivon', type: 'FMC', focalLengthmm: '17', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Olivon', type: 'FMC', focalLengthmm: '22', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Olivon', type: 'FMC', focalLengthmm: '32', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Olivon', type: 'HD', focalLengthmm: '2.5', fieldStopmm: '', apparentField: '58'},
		{manufacturer: 'Olivon', type: 'HD', focalLengthmm: '4', fieldStopmm: '', apparentField: '58'},
		{manufacturer: 'Olivon', type: 'HD', focalLengthmm: '5', fieldStopmm: '', apparentField: '58'},
		{manufacturer: 'Olivon', type: 'HD', focalLengthmm: '6', fieldStopmm: '', apparentField: '58'},
		{manufacturer: 'Olivon', type: 'HD', focalLengthmm: '7', fieldStopmm: '', apparentField: '58'},
		{manufacturer: 'Olivon', type: 'HD', focalLengthmm: '15', fieldStopmm: '', apparentField: '58'},
		{manufacturer: 'Olivon', type: 'HD', focalLengthmm: '20', fieldStopmm: '', apparentField: '58'},
		{manufacturer: 'Omegon', type: 'Panorama II', focalLengthmm: '5', fieldStopmm: '', apparentField: '100'},
		{manufacturer: 'Omegon', type: 'Panorama II', focalLengthmm: '10', fieldStopmm: '', apparentField: '100'},
		{manufacturer: 'Omegon', type: 'Panorama II', focalLengthmm: '15', fieldStopmm: '', apparentField: '100'},
		{manufacturer: 'Omegon', type: 'Panorama II', focalLengthmm: '21', fieldStopmm: '', apparentField: '100'},
		{manufacturer: 'Orion', type: 'Sirius/Highlight', focalLengthmm: '6.3', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Sirius/Highlight', focalLengthmm: '7.5', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Sirius/Highlight', focalLengthmm: '10', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Sirius/Highlight', focalLengthmm: '12.5', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Sirius/Highlight', focalLengthmm: '17', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Sirius/Highlight', focalLengthmm: '20', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Sirius/Highlight', focalLengthmm: '26', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Sirius/Highlight', focalLengthmm: '32', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Sirius/Highlight', focalLengthmm: '40', fieldStopmm: '', apparentField: '43'}, 
		{manufacturer: 'Orion', type: 'Epic ED-2', focalLengthmm: '3.7', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Orion', type: 'Epic ED-2', focalLengthmm: '5.1', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Orion', type: 'Epic ED-2', focalLengthmm: '7.5', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Orion', type: 'Epic ED-2', focalLengthmm: '9.5', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Orion', type: 'Epic ED-2', focalLengthmm: '12.3', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Orion', type: 'Epic ED-2', focalLengthmm: '14', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Orion', type: 'Epic ED-2', focalLengthmm: '18', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Orion', type: 'Epic ED-2', focalLengthmm: '22', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Orion', type: 'Epic ED-2', focalLengthmm: '25', fieldStopmm: '', apparentField: '55'},
		{manufacturer: 'Orion', type: 'Expanse', focalLengthmm: '6', fieldStopmm: '', apparentField: '66'},
		{manufacturer: 'Orion', type: 'Expanse', focalLengthmm: '9', fieldStopmm: '', apparentField: '66'},
		{manufacturer: 'Orion', type: 'Expanse', focalLengthmm: '15', fieldStopmm: '', apparentField: '66'},
		{manufacturer: 'Orion', type: 'Expanse', focalLengthmm: '20', fieldStopmm: '', apparentField: '66'},
		{manufacturer: 'Orion', type: 'Stratus', focalLengthmm: '3.5', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Orion', type: 'Stratus', focalLengthmm: '5', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Orion', type: 'Stratus', focalLengthmm: '8', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Orion', type: 'Stratus', focalLengthmm: '13', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Orion', type: 'Stratus', focalLengthmm: '17', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Orion', type: 'Stratus', focalLengthmm: '21', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Orion', type: 'Stratus', focalLengthmm: '30', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Orion', type: 'Stratus', focalLengthmm: '35', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Orion', type: 'Ultrascopic', focalLengthmm: '3.8', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Ultrascopic', focalLengthmm: '5', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Ultrascopic', focalLengthmm: '7.5', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Ultrascopic', focalLengthmm: '10', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Ultrascopic', focalLengthmm: '15', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Ultrascopic', focalLengthmm: '20', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Ultrascopic', focalLengthmm: '25', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Ultrascopic', focalLengthmm: '30', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Ultrascopic', focalLengthmm: '35', fieldStopmm: '', apparentField: '49'},
		{manufacturer: 'Orion', type: 'DeepView', focalLengthmm: '35', fieldStopmm: '', apparentField: '56'},
		{manufacturer: 'Orion', type: 'DeepView', focalLengthmm: '42', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Orion', type: 'Optiluxe', focalLengthmm: '32', fieldStopmm: '', apparentField: '58'},
		{manufacturer: 'Orion', type: 'Optiluxe', focalLengthmm: '40', fieldStopmm: '', apparentField: '62'},
		{manufacturer: 'Orion', type: 'Optiluxe', focalLengthmm: '50', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Pentax', type: 'XW', focalLengthmm: '20', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Pentax', type: 'XW', focalLengthmm: '14', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Pentax', type: 'XW', focalLengthmm: '10', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Pentax', type: 'XW', focalLengthmm: '7', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Pentax', type: 'XW', focalLengthmm: '5', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Pentax', type: 'XW', focalLengthmm: '3.5', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'Stellarvue', type: 'Optimus', focalLengthmm: '3.6', fieldStopmm: '', apparentField: '110'},
		{manufacturer: 'Stellarvue', type: 'Optimus', focalLengthmm: '4.7', fieldStopmm: '', apparentField: '110'},
		{manufacturer: 'Stellarvue', type: 'Optimus', focalLengthmm: '9', fieldStopmm: '', apparentField: '100'},
		{manufacturer: 'Stellarvue', type: 'Optimus', focalLengthmm: '20', fieldStopmm: '', apparentField: '100'},
		{manufacturer: 'Stellarvue', type: 'Planetary', focalLengthmm: '4.9', fieldStopmm: '8.5', apparentField: '55'},
		{manufacturer: 'Stellarvue', type: 'Planetary', focalLengthmm: '6.12', fieldStopmm: '9', apparentField: '55'},
		{manufacturer: 'Stellarvue', type: 'Standard', focalLengthmm: '9', fieldStopmm: '7.5', apparentField: '50'},
		{manufacturer: 'Stellarvue', type: 'Standard', focalLengthmm: '25', fieldStopmm: '21.5', apparentField: '50'},
		{manufacturer: 'Stellarvue', type: 'Ultra Wide Angle', focalLengthmm: '4', fieldStopmm: '7.5', apparentField: '82'},
		{manufacturer: 'Stellarvue', type: 'Ultra Wide Angle', focalLengthmm: '8', fieldStopmm: '13.6', apparentField: '82'},
		{manufacturer: 'Stellarvue', type: 'Ultra Wide Angle', focalLengthmm: '15', fieldStopmm: '25', apparentField: '82'},
		{manufacturer: 'Surplus Shed', type: 'Series 500 Plossl', focalLengthmm: '25', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Surplus Shed', type: 'Series 500 Plossl', focalLengthmm: '10', fieldStopmm: '', apparentField: '51'},
		{manufacturer: 'Surplus Shed', type: 'Series 500 Plossl', focalLengthmm: '6.5', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Surplus Shed', type: 'Pro Kellner', focalLengthmm: '25', fieldStopmm: '', apparentField: '40'},
		{manufacturer: 'Svbony', type: '72 Deg Aspheric', focalLengthmm: '9', fieldStopmm: '', apparentField: '72'},
		{manufacturer: 'Svbony', type: '72 Deg Aspheric', focalLengthmm: '18', fieldStopmm: '', apparentField: '72'},
		{manufacturer: 'Svbony', type: '72 Deg Aspheric', focalLengthmm: '34', fieldStopmm: '', apparentField: '72'},
		{manufacturer: 'Svbony', type: 'SV113', focalLengthmm: '9', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Svbony', type: 'SV113', focalLengthmm: '12', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Svbony', type: 'SV113', focalLengthmm: '16', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'Svbony', type: 'SV113', focalLengthmm: '20', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'Svbony', type: '68 Deg', focalLengthmm: '6', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Svbony', type: '68 Deg', focalLengthmm: '9', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Svbony', type: '68 Deg', focalLengthmm: '15', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Svbony', type: '68 Deg', focalLengthmm: '20', fieldStopmm: '', apparentField: '68'},
		{manufacturer: 'Svbony', type: '66 Deg', focalLengthmm: '6', fieldStopmm: '', apparentField: '66'},
		{manufacturer: 'Svbony', type: '66 Deg', focalLengthmm: '9', fieldStopmm: '', apparentField: '66'},
		{manufacturer: 'Svbony', type: '66 Deg', focalLengthmm: '15', fieldStopmm: '', apparentField: '66'},
		{manufacturer: 'Svbony', type: '66 Deg', focalLengthmm: '20', fieldStopmm: '', apparentField: '66'},
		{manufacturer: 'Takahashi', type: 'LE', focalLengthmm: '5', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Takahashi', type: 'LE', focalLengthmm: '7.5', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Takahashi', type: 'LE', focalLengthmm: '12.5', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Takahashi', type: 'LE', focalLengthmm: '18', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Takahashi', type: 'LE', focalLengthmm: '24', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Takahashi', type: 'LE', focalLengthmm: '30', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'Takahashi', type: 'LE', focalLengthmm: '50', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '17.3', fieldStopmm: '21.2', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '14', fieldStopmm: '17.3', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '12', fieldStopmm: '15', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '10', fieldStopmm: '12.7', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '8', fieldStopmm: '9.9', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '6', fieldStopmm: '7.6', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '4.5', fieldStopmm: '5.6', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '3.5', fieldStopmm: '4.4', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Ethos', focalLengthmm: '21', fieldStopmm: '36.2', apparentField: '100'},
		{manufacturer: 'TeleVue', type: 'Ethos', focalLengthmm: '17', fieldStopmm: '29.6', apparentField: '100'},
		{manufacturer: 'TeleVue', type: 'Ethos', focalLengthmm: '13', fieldStopmm: '22.3', apparentField: '100'},
		{manufacturer: 'TeleVue', type: 'Ethos', focalLengthmm: '10', fieldStopmm: '17.7', apparentField: '100'},
		{manufacturer: 'TeleVue', type: 'Ethos', focalLengthmm: '8', fieldStopmm: '13.9', apparentField: '100'},
		{manufacturer: 'TeleVue', type: 'Ethos', focalLengthmm: '6', fieldStopmm: '10.4', apparentField: '100'},
		{manufacturer: 'TeleVue', type: 'Ethos SX', focalLengthmm: '4.7', fieldStopmm: '8.94', apparentField: '110'},
		{manufacturer: 'TeleVue', type: 'Ethos SX', focalLengthmm: '3.7', fieldStopmm: '7.04', apparentField: '110'},
		{manufacturer: 'TeleVue', type: 'Nagler 5', focalLengthmm: '31', fieldStopmm: '42', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 5', focalLengthmm: '26', fieldStopmm: '35', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 4', focalLengthmm: '22', fieldStopmm: '31.1', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 5', focalLengthmm: '20', fieldStopmm: '27.4', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 4', focalLengthmm: '17', fieldStopmm: '24.3', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 5', focalLengthmm: '16', fieldStopmm: '22.1', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '13', fieldStopmm: '17.6', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 4', focalLengthmm: '12', fieldStopmm: '17.1', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '11', fieldStopmm: '14.9', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '9', fieldStopmm: '12.4', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '7', fieldStopmm: '9.7', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '5', fieldStopmm: '7', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '3.5', fieldStopmm: '4.8', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '2.5', fieldStopmm: '3.4', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler (orig)', focalLengthmm: '4.8', fieldStopmm: '6.6', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler (orig)', focalLengthmm: '7', fieldStopmm: '9.4', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler (orig)', focalLengthmm: '9', fieldStopmm: '12.3', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler (orig)', focalLengthmm: '11', fieldStopmm: '14.9', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler (orig)', focalLengthmm: '13', fieldStopmm: '17.8', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 2', focalLengthmm: '12', fieldStopmm: '16.4', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 2', focalLengthmm: '16', fieldStopmm: '21.9', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 2', focalLengthmm: '20', fieldStopmm: '27.4', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Panoptic', focalLengthmm: '41', fieldStopmm: '46', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Panoptic', focalLengthmm: '35', fieldStopmm: '38.7', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Panoptic', focalLengthmm: '27', fieldStopmm: '30.5', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Panoptic', focalLengthmm: '24', fieldStopmm: '27', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Panoptic', focalLengthmm: '19', fieldStopmm: '21.3', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Panoptic (orig)', focalLengthmm: '15', fieldStopmm: '17.1', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Panoptic (orig)', focalLengthmm: '22', fieldStopmm: '25', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '55', fieldStopmm: '46', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '40', fieldStopmm: '27', apparentField: '43'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '32', fieldStopmm: '27', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '25', fieldStopmm: '21.2', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '20', fieldStopmm: '17.1', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '15', fieldStopmm: '12.6', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '11', fieldStopmm: '9.1', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '8', fieldStopmm: '6.5', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl (orig)', focalLengthmm: '7.4', fieldStopmm: '6.2', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl (orig)', focalLengthmm: '10.5', fieldStopmm: '8.7', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl (orig)', focalLengthmm: '13', fieldStopmm: '10.8', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl (orig)', focalLengthmm: '17', fieldStopmm: '14.3', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl (orig)', focalLengthmm: '21', fieldStopmm: '18', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl (orig)', focalLengthmm: '26', fieldStopmm: '22.1', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '5', fieldStopmm: '5.3', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '6', fieldStopmm: '6.3', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '8', fieldStopmm: '8.3', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '10', fieldStopmm: '10.5', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '12', fieldStopmm: '12.6', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '14', fieldStopmm: '14.4', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '18', fieldStopmm: '18.3', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Wide Field', focalLengthmm: '15', fieldStopmm: '15.4', apparentField: '65'},
		{manufacturer: 'TeleVue', type: 'Wide Field', focalLengthmm: '19', fieldStopmm: '19.6', apparentField: '65'},
		{manufacturer: 'TeleVue', type: 'Wide Field', focalLengthmm: '24', fieldStopmm: '24.7', apparentField: '65'},
		{manufacturer: 'TeleVue', type: 'Wide Field', focalLengthmm: '32', fieldStopmm: '33', apparentField: '65'},
		{manufacturer: 'TeleVue', type: 'Wide Field', focalLengthmm: '40', fieldStopmm: '41.2', apparentField: '65'},
		{manufacturer: 'University Optics', type: 'Konig II', focalLengthmm: '12', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'University Optics', type: 'Konig II', focalLengthmm: '16', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'University Optics', type: 'Konig II', focalLengthmm: '24', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'University Optics', type: 'Konig II', focalLengthmm: '32', fieldStopmm: '', apparentField: '52'},
		{manufacturer: 'University Optics', type: 'Konig', focalLengthmm: '32', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'University Optics', type: 'Konig MK-70', focalLengthmm: '25', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'University Optics', type: 'Konig MK-70', focalLengthmm: '40', fieldStopmm: '', apparentField: '70'},
		{manufacturer: 'University Optics', type: 'Konig Plossl', focalLengthmm: '55', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'University Optics', type: 'Ortho', focalLengthmm: '4', fieldStopmm: '', apparentField: '42'},
		{manufacturer: 'University Optics', type: 'Ortho', focalLengthmm: '5', fieldStopmm: '', apparentField: '42'},
		{manufacturer: 'University Optics', type: 'Ortho', focalLengthmm: '7', fieldStopmm: '', apparentField: '42'},
		{manufacturer: 'University Optics', type: 'Ortho', focalLengthmm: '9', fieldStopmm: '', apparentField: '42'},
		{manufacturer: 'University Optics', type: 'Ortho', focalLengthmm: '12.5', fieldStopmm: '', apparentField: '42'},
		{manufacturer: 'University Optics', type: 'Ortho', focalLengthmm: '18', fieldStopmm: '', apparentField: '42'},
		{manufacturer: 'University Optics', type: 'Ortho', focalLengthmm: '25', fieldStopmm: '', apparentField: '42'},
		{manufacturer: 'University Optics', type: 'Super Erfle', focalLengthmm: '16', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'University Optics', type: 'Super Erfle', focalLengthmm: '20', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'University Optics', type: 'Super Erfle', focalLengthmm: '25', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'University Optics', type: 'Wide Angle Plossl', focalLengthmm: '12', fieldStopmm: '', apparentField: '60'},
		{manufacturer: 'Vernonscope', type: 'Brandon', focalLengthmm: '6', fieldStopmm: '4.5', apparentField: '42'},
		{manufacturer: 'Vernonscope', type: 'Brandon', focalLengthmm: '8', fieldStopmm: '5.9', apparentField: '43'},
		{manufacturer: 'Vernonscope', type: 'Brandon', focalLengthmm: '12', fieldStopmm: '8.8', apparentField: '43'},
		{manufacturer: 'Vernonscope', type: 'Brandon', focalLengthmm: '16', fieldStopmm: '11.9', apparentField: '43'},
		{manufacturer: 'Vernonscope', type: 'Brandon', focalLengthmm: '24', fieldStopmm: '21.5', apparentField: '52'},
		{manufacturer: 'Vernonscope', type: 'Brandon', focalLengthmm: '32', fieldStopmm: '25.3', apparentField: '45'},
		{manufacturer: 'Vernonscope', type: 'Brandon', focalLengthmm: '48', fieldStopmm: '37', apparentField: '45'},
		{manufacturer: 'Vixen', type: 'HR', focalLengthmm: '1.6', fieldStopmm: '', apparentField: '42'},
		{manufacturer: 'Vixen', type: 'HR', focalLengthmm: '2', fieldStopmm: '', apparentField: '42'},
		{manufacturer: 'Vixen', type: 'HR', focalLengthmm: '2.4', fieldStopmm: '', apparentField: '42'},
		{manufacturer: 'Vixen', type: 'Lanthanum', focalLengthmm: '30', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'Vixen', type: 'Lanthanum', focalLengthmm: '50', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Vixen', type: 'Lanthanum LV', focalLengthmm: '2.5', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Vixen', type: 'Lanthanum LV', focalLengthmm: '4', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Vixen', type: 'Lanthanum LV', focalLengthmm: '5', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Vixen', type: 'Lanthanum LV', focalLengthmm: '6', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Vixen', type: 'Lanthanum LV', focalLengthmm: '9', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Vixen', type: 'Lanthanum LV', focalLengthmm: '10', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Vixen', type: 'Lanthanum LV', focalLengthmm: '12', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Vixen', type: 'Lanthanum LV', focalLengthmm: '15', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Vixen', type: 'Lanthanum LV', focalLengthmm: '20', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Vixen', type: 'Lanthanum LV', focalLengthmm: '25', fieldStopmm: '', apparentField: '45'},
		{manufacturer: 'Vixen', type: 'Lanthanum NLVW', focalLengthmm: '30', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'Vixen', type: 'Lanthanum Wide LVW', focalLengthmm: '3.5', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'Vixen', type: 'Lanthanum Wide LVW', focalLengthmm: '5', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'Vixen', type: 'Lanthanum Wide LVW', focalLengthmm: '8', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'Vixen', type: 'Lanthanum Wide LVW', focalLengthmm: '13', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'Vixen', type: 'Lanthanum Wide LVW', focalLengthmm: '17', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'Vixen', type: 'Lanthanum Wide LVW', focalLengthmm: '22', fieldStopmm: '', apparentField: '65'},
		{manufacturer: 'Vixen', type: 'Plossl NPL', focalLengthmm: '4', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'Plossl NPL', focalLengthmm: '6', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'Plossl NPL', focalLengthmm: '8', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'Plossl NPL', focalLengthmm: '10', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'Plossl NPL', focalLengthmm: '15', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'Plossl NPL', focalLengthmm: '20', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'Plossl NPL', focalLengthmm: '25', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'Plossl NPL', focalLengthmm: '30', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'Plossl NPL', focalLengthmm: '40', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'SLV', focalLengthmm: '2.5', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'SLV', focalLengthmm: '4', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'SLV', focalLengthmm: '5', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'SLV', focalLengthmm: '6', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'SLV', focalLengthmm: '9', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'SLV', focalLengthmm: '10', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'SLV', focalLengthmm: '12', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'SLV', focalLengthmm: '15', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'SLV', focalLengthmm: '20', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'SLV', focalLengthmm: '25', fieldStopmm: '', apparentField: '50'},
		{manufacturer: 'Vixen', type: 'SSW', focalLengthmm: '3.5', fieldStopmm: '', apparentField: '83'},
		{manufacturer: 'Vixen', type: 'SSW', focalLengthmm: '5', fieldStopmm: '', apparentField: '83'},
		{manufacturer: 'Vixen', type: 'SSW', focalLengthmm: '7', fieldStopmm: '', apparentField: '83'},
		{manufacturer: 'Vixen', type: 'SSW', focalLengthmm: '10', fieldStopmm: '', apparentField: '83'},
		{manufacturer: 'Vixen', type: 'SSW', focalLengthmm: '14', fieldStopmm: '', apparentField: '83'},
		{manufacturer: 'Vixen', type: 'Wide Angle', focalLengthmm: '42', fieldStopmm: '', apparentField: '72'},
		{manufacturer: 'Williams Optics', type: 'SWAN', focalLengthmm: '40', fieldStopmm: '46', apparentField: '70'},
		{manufacturer: 'Williams Optics', type: 'SWAN', focalLengthmm: '33', fieldStopmm: '41', apparentField: '72'},
		{manufacturer: 'Williams Optics', type: 'SWAN', focalLengthmm: '25', fieldStopmm: '33', apparentField: '72'},
		{manufacturer: 'Williams Optics', type: 'SWAN', focalLengthmm: '20', fieldStopmm: '26', apparentField: '72'},
		{manufacturer: 'Williams Optics', type: 'SWAN', focalLengthmm: '15', fieldStopmm: '19', apparentField: '72'},
		{manufacturer: 'Williams Optics', type: 'SWAN', focalLengthmm: '9', fieldStopmm: '13', apparentField: '72'}
	]
};
