MLB.eyepiecesJson = {
	'eyepieces': [
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '55', fieldStopmm: '46', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '40', fieldStopmm: '27', apparentField: '43'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '32', fieldStopmm: '27', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '25', fieldStopmm: '21.2', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '20', fieldStopmm: '17.1', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '15', fieldStopmm: '12.6', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '11', fieldStopmm: '9.1', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '8', fieldStopmm: '6.5', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Panoptic', focalLengthmm: '41', fieldStopmm: '46', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Panoptic', focalLengthmm: '35', fieldStopmm: '38.7', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Panoptic', focalLengthmm: '27', fieldStopmm: '30.5', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Panoptic', focalLengthmm: '24', fieldStopmm: '27', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Panoptic', focalLengthmm: '19', fieldStopmm: '21.3', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '17.3', fieldStopmm: '21.2', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '14', fieldStopmm: '17.3', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '12', fieldStopmm: '15', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '10', fieldStopmm: '12.7', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '8', fieldStopmm: '9.9', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '6', fieldStopmm: '7.6', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '4.5', fieldStopmm: '5.6', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Delos', focalLengthmm: '3.5', fieldStopmm: '4.4', apparentField: '72'},
		{manufacturer: 'TeleVue', type: 'Nagler 5', focalLengthmm: '31', fieldStopmm: '42', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 5', focalLengthmm: '26', fieldStopmm: '35', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 4', focalLengthmm: '22', fieldStopmm: '31.1', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 5', focalLengthmm: '20', fieldStopmm: '27.4', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 4', focalLengthmm: '17', fieldStopmm: '24.3', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 5', focalLengthmm: '16', fieldStopmm: '22.1', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '13', fieldStopmm: '17.6', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 4', focalLengthmm: '12', fieldStopmm: '17.1', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '11', fieldStopmm: '14.9', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '9', fieldStopmm: '12.4', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '7', fieldStopmm: '9.7', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '5', fieldStopmm: '7', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '3.5', fieldStopmm: '4.8', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 6', focalLengthmm: '2.5', fieldStopmm: '3.4', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Ethos', focalLengthmm: '21', fieldStopmm: '36.2', apparentField: '100'},
		{manufacturer: 'TeleVue', type: 'Ethos', focalLengthmm: '17', fieldStopmm: '29.6', apparentField: '100'},
		{manufacturer: 'TeleVue', type: 'Ethos', focalLengthmm: '13', fieldStopmm: '22.3', apparentField: '100'},
		{manufacturer: 'TeleVue', type: 'Ethos', focalLengthmm: '10', fieldStopmm: '17.7', apparentField: '100'},
		{manufacturer: 'TeleVue', type: 'Ethos', focalLengthmm: '8', fieldStopmm: '13.9', apparentField: '100'},
		{manufacturer: 'TeleVue', type: 'Ethos', focalLengthmm: '6', fieldStopmm: '10.4', apparentField: '100'},
		{manufacturer: 'TeleVue', type: 'Ethos SX', focalLengthmm: '4.7', fieldStopmm: '8.94', apparentField: '110'},
		{manufacturer: 'TeleVue', type: 'Ethos SX', focalLengthmm: '3.7', fieldStopmm: '7.04', apparentField: '110'},
		{manufacturer: 'TeleVue', type: 'Nagler', focalLengthmm: '4.8', fieldStopmm: '6.6', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler', focalLengthmm: '7', fieldStopmm: '9.4', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler', focalLengthmm: '9', fieldStopmm: '12.3', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler', focalLengthmm: '11', fieldStopmm: '14.9', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler', focalLengthmm: '13', fieldStopmm: '17.8', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 2', focalLengthmm: '12', fieldStopmm: '16.4', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 2', focalLengthmm: '16', fieldStopmm: '21.9', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Nagler 2', focalLengthmm: '20', fieldStopmm: '27.4', apparentField: '82'},
		{manufacturer: 'TeleVue', type: 'Wide Field', focalLengthmm: '15', fieldStopmm: '15.4', apparentField: '65'},
		{manufacturer: 'TeleVue', type: 'Wide Field', focalLengthmm: '19', fieldStopmm: '19.6', apparentField: '65'},
		{manufacturer: 'TeleVue', type: 'Wide Field', focalLengthmm: '24', fieldStopmm: '24.7', apparentField: '65'},
		{manufacturer: 'TeleVue', type: 'Wide Field', focalLengthmm: '32', fieldStopmm: '33', apparentField: '65'},
		{manufacturer: 'TeleVue', type: 'Wide Field', focalLengthmm: '40', fieldStopmm: '41.2', apparentField: '65'},
		{manufacturer: 'TeleVue', type: 'Panoptic', focalLengthmm: '15', fieldStopmm: '17.1', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Panoptic', focalLengthmm: '22', fieldStopmm: '25', apparentField: '68'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '5', fieldStopmm: '5.3', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '6', fieldStopmm: '6.3', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '8', fieldStopmm: '8.3', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '10', fieldStopmm: '10.5', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '12', fieldStopmm: '12.6', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '14', fieldStopmm: '14.4', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Radian', focalLengthmm: '18', fieldStopmm: '18.3', apparentField: '60'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '7.4', fieldStopmm: '6.2', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '10.5', fieldStopmm: '8.7', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '13', fieldStopmm: '10.8', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '17', fieldStopmm: '14.3', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '21', fieldStopmm: '18', apparentField: '50'},
		{manufacturer: 'TeleVue', type: 'Plossl', focalLengthmm: '26', fieldStopmm: '22.1', apparentField: '50'}
	]
};


