MLB.focusersJson = {
	'focusers': [
		{manufacturer: 'Antares', model: '2" Low Profile Crayford',  rackedInHeightInches: '1.89', travelInches: '2.7'},
		{manufacturer: 'Antares', model: '2" Low Profile Crayford gear drive',  rackedInHeightInches: '1.89', travelInches: '2.7'},
		{manufacturer: 'Baaader', model: '2" Diamond Steeltrack',  rackedInHeightInches: '1.97', travelInches: '1.57'},
		{manufacturer: 'Destiny', model: 'Super Low Profile Helical',  rackedInHeightInches: '0.75', travelInches: '0.875'},
		{manufacturer: 'Guan Sheng Optical', model: '2" Crayford',  rackedInHeightInches: '2.87', travelInches: '1.57'},
		{manufacturer: 'Guan Sheng Optical', model: '2" Crayford single speed',  rackedInHeightInches: '2.83', travelInches: '1.38'},
		{manufacturer: 'Guan Sheng Optical', model: '2" Linear Bearing Crayford',  rackedInHeightInches: '3.05', travelInches: '2'},
		{manufacturer: 'JMI', model: 'EV-1n',  rackedInHeightInches: '2.3', travelInches: '1.7'},
		{manufacturer: 'JMI', model: 'EV-2n',  rackedInHeightInches: '2.3', travelInches: '1.7'},
		{manufacturer: 'JMI', model: 'EV-3n',  rackedInHeightInches: '2.3', travelInches: '1.7'},
		{manufacturer: 'JMI', model: 'RCF-1',  rackedInHeightInches: '1.8', travelInches: '1.5'},
		{manufacturer: 'KineOptics', model: 'HC-2',  rackedInHeightInches: '0.975', travelInches: '1.29'},
		{manufacturer: 'KineOptics', model: 'HC-2A',  rackedInHeightInches: '1.11', travelInches: '1'},
		{manufacturer: 'MoonLite', model: 'CR 1.5',  rackedInHeightInches: '1.45', travelInches: '1.5'},
		{manufacturer: 'MoonLite', model: 'CR+compression ring 1.5',  rackedInHeightInches: '1.825', travelInches: '1.5'},
		{manufacturer: 'MoonLite', model: 'CR 1.75',  rackedInHeightInches: '1.45', travelInches: '1.75'},
		{manufacturer: 'MoonLite', model: 'CR+compression ring 1.75',  rackedInHeightInches: '1.825', travelInches: '1.75'},
		{manufacturer: 'MoonLite', model: 'CR 2.0',  rackedInHeightInches: '1.45', travelInches: '2.0'},
		{manufacturer: 'MoonLite', model: 'CR+compression ring 2.0',  rackedInHeightInches: '1.825', travelInches: '2.0'},
		{manufacturer: 'MoonLite', model: 'CR 2.37',  rackedInHeightInches: '1.45', travelInches: '2.37'},
		{manufacturer: 'MoonLite', model: 'CR+compression ring 2.37',  rackedInHeightInches: '1.825', travelInches: '2.37'},
		{manufacturer: 'MoonLite', model: 'CR 2.75',  rackedInHeightInches: '1.45', travelInches: '2.75'},
		{manufacturer: 'MoonLite', model: 'CR+compression ring 2.75',  rackedInHeightInches: '1.825', travelInches: '2.75'},
		{manufacturer: 'MoonLite', model: 'CR 1.5 low position',  rackedInHeightInches: '2.25', travelInches: '1.5'},
		{manufacturer: 'MoonLite', model: 'CR+compression ring 1.5 low position',  rackedInHeightInches: '2.25', travelInches: '1.5'},
		{manufacturer: 'Orion', model: '2" Crayford-Style',  rackedInHeightInches: '2.6875', travelInches: '1.4'},
		{manufacturer: 'Orion', model: 'Orion 2" Low-Profile Dual-Speed',  rackedInHeightInches: '2.283', travelInches: '2.5'},
		{manufacturer: 'Starlight Instruments', model: 'FTF2008BCR',  rackedInHeightInches: '1.405', travelInches: '0.8'},
		{manufacturer: 'Starlight Instruments', model: 'FTF2015BCR',  rackedInHeightInches: '1.405', travelInches: '1.6'},
		{manufacturer: 'Starlight Instruments', model: 'FTF2020BCR',  rackedInHeightInches: '1.405', travelInches: '2.1'},
		{manufacturer: 'Starlight Instruments', model: 'FTF2025BCR',  rackedInHeightInches: '1.405', travelInches: '2.6'},
		{manufacturer: 'Starlight Instruments', model: 'FTF2015BCR-RP',  rackedInHeightInches: '1.905', travelInches: '1.6'}
		//{manufacturer: '', model: '',  rackedInHeightInches: '', travelInches: ''},
	]
};
