MLB.focusersJson = {
	'focusers': [
		{Manufacturer: 'Antares', model: '2" Low Profile Crayford',  rackedInHeightInches: '1.89', focuserTravelInches: '2.7'},
		{Manufacturer: 'Antares', model: '2" Low Profile Crayford gear drive',  rackedInHeightInches: '1.89', focuserTravelInches: '2.7'},
		{Manufacturer: 'Baaader', model: '2" Diamond Steeltrack',  rackedInHeightInches: '1.97', focuserTravelInches: '1.57'},
		{Manufacturer: 'Destiny', model: 'Super Low Profile Helical',  rackedInHeightInches: '0.75', focuserTravelInches: '0.875'},
		{Manufacturer: 'Guan Sheng Optical', model: '2" Crayford',  rackedInHeightInches: '2.87', focuserTravelInches: '1.57'},
		{Manufacturer: 'Guan Sheng Optical', model: '2" Crayford single speed',  rackedInHeightInches: '2.83', focuserTravelInches: '1.38'},
		{Manufacturer: 'Guan Sheng Optical', model: '2" Linear Bearing Crayford',  rackedInHeightInches: '3.05', focuserTravelInches: '2'},
		{Manufacturer: 'KineOptics', model: 'HC-2',  rackedInHeightInches: '0.975', focuserTravelInches: '1.29'},
		{Manufacturer: 'KineOptics', model: 'HC-2A',  rackedInHeightInches: '1.11', focuserTravelInches: '1'},
		{Manufacturer: 'MoonLite', model: 'CR',  rackedInHeightInches: '1.45', focuserTravelInches: '1.5'},
		{Manufacturer: 'MoonLite', model: 'CR+compression ring',  rackedInHeightInches: '1.825', focuserTravelInches: '1.5'},
		{Manufacturer: 'MoonLite', model: 'CR',  rackedInHeightInches: '1.45', focuserTravelInches: '1.75'},
		{Manufacturer: 'MoonLite', model: 'CR+compression ring',  rackedInHeightInches: '1.825', focuserTravelInches: '1.75'},
		{Manufacturer: 'MoonLite', model: 'CR',  rackedInHeightInches: '1.45', focuserTravelInches: '2.0'},
		{Manufacturer: 'MoonLite', model: 'CR+compression ring',  rackedInHeightInches: '1.825', focuserTravelInches: '2.0'},
		{Manufacturer: 'MoonLite', model: 'CR',  rackedInHeightInches: '1.45', focuserTravelInches: '2.37'},
		{Manufacturer: 'MoonLite', model: 'CR+compression ring',  rackedInHeightInches: '1.825', focuserTravelInches: '2.37'},
		{Manufacturer: 'MoonLite', model: 'CR',  rackedInHeightInches: '1.45', focuserTravelInches: '2.75'},
		{Manufacturer: 'MoonLite', model: 'CR+compression ring',  rackedInHeightInches: '1.825', focuserTravelInches: '2.75'},
		{Manufacturer: 'MoonLite', model: ,  rackedInHeightInches: '', focuserTravelInches: ''},
		{Manufacturer: 'MoonLite', model: 'CR+compression ring',  rackedInHeightInches: '2.25', focuserTravelInches: '1.5'},
		{Manufacturer: 'Orion', model: '2" Crayford-Style Telescope Focuser',  rackedInHeightInches: '2.6875', focuserTravelInches: '1.4'},
		{Manufacturer: 'Orion', model: 'Orion 2" Low-Profile Dual-Speed Hybrid Reflector Focuser',  rackedInHeightInches: '2.283', focuserTravelInches: ''},
		{Manufacturer: 'Starlight Instruments', model: 'FTF2008BCR',  rackedInHeightInches: '1.405', focuserTravelInches: '0.8'},
		{Manufacturer: 'Starlight Instruments', model: 'FTF2015BCR',  rackedInHeightInches: '1.405', focuserTravelInches: '1.6'},
		{Manufacturer: 'Starlight Instruments', model: 'FTF2020BCR',  rackedInHeightInches: '1.405', focuserTravelInches: '2.1'},
		{Manufacturer: 'Starlight Instruments', model: 'FTF2025BCR',  rackedInHeightInches: '1.405', focuserTravelInches: '2.6'},
		{Manufacturer: 'Starlight Instruments', model: 'FTF2015BCR-RP',  rackedInHeightInches: '1.905', focuserTravelInches: '1.6'},
		{Manufacturer: 'JMI', model: 'EV-1n',  rackedInHeightInches: '2.3', focuserTravelInches: '1.7'},
		{Manufacturer: 'JMI', model: 'EV-2n',  rackedInHeightInches: '2.3', focuserTravelInches: '1.7'},
		{Manufacturer: 'JMI', model: 'EV-3n',  rackedInHeightInches: '2.3', focuserTravelInches: '1.7'},
		{Manufacturer: 'JMI', model: 'RCF-1',  rackedInHeightInches: '1.8', focuserTravelInches: '1.5'}
		//{Manufacturer: '', model: '',  rackedInHeightInches: '', focuserTravelInches: ''},
	]
};
