MLB.mountTypesJson = {
	'mountTypes': [

		// tightly coupled to the JS code that processes teh data;
		// a section header must have ':' mountType field
	
		{mountType: '<br><b>Altazimuth</b>:', priAxisAlign: '', canMoveToPriAxisPole: '', canMoveThruPriAxisPole: '', priAxisFullyRotates: '', meridianFlipPossible: '', meridianFlipRequired: '', notes: ''},
		
		{mountType: 'Dobsonian', priAxisAlign: 'Geographic', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'The Dobsonian: hugely popular; designed for larger apertures; build from common materials using simple tools but no simple motorized tracking<br><a href="8inchDobs.html" target="_blank">my 8 inch Dobs</a><br><a href="Morse/The Morse Equatorial to Altazimuth Transformer Mount.html" target="_blank">the Morse Equatorial to Altazimuth Transformer</a><br><a href="EarlOfCrawford/EarlOfCrawford.html" target="_blank">Earl of Crawford tracking arm</a><br><br>'},
		{mountType: 'AltazFlexRocker', priAxisAlign: 'Geographic', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Rocker shrunk and turned upside down for less weight, lower eyepiece height but azimuth pads can sweep up dust<br><a href="ZipDob/ZipDobII/side.JPG" target="_blank">my ZipDob</a><br><a href="FlexRocker/FlexRockers.html" target="_blank">flex rockers</a><br><br>'},
		{mountType: 'AltazFork', priAxisAlign: 'Geographic', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Vertically aimed fork<br><a href="8 inch blue and black altaz.jpg" target="_blank">my 8 inch blue and black fork altaz</a><br><a href="17inch Dob.html" target="_blank">17.5 inch Dob</a><br><br>'},
		{mountType: 'AltazSingleArmFork', priAxisAlign: 'Geographic', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'A single fork arm on one side, traditional Dob bearing on the other<br><a href="20inch.html" target="_blank">my 20 inch single arm Dob</a><br><br>'},
		{mountType: 'AltazTiltedFork', priAxisAlign: 'Geographic', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Tilted fork; used in small refractors: makes zenith accessible at cost of some imbalance<br><a href="https://tinyurl.com/y84hhsrm" target="_blank">image search</a><br><br>'},
		{mountType: 'TriDob', priAxisAlign: 'Geographic', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Altitude bearing composed of two forward sectors and one tailfin allowing the altitude rims to fold up against the mirror box<br><a href="trilateral.html" target="_blank">my TriDob</a><br><br>'},
		{mountType: 'AltAlt', priAxisAlign: 'Geographic', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'no', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Think horizontal yoke<br><a href="https://www.youtube.com/watch?v=UjDujtVoRYc" target=_blank">alt alt 1 meter</a><br><br>'},

		{mountType: '<br><b>Three-axis</b>:', priAxisAlign: '', canMoveToPriAxisPole: '', canMoveThruPriAxisPole: '', priAxisFullyRotates: '', meridianFlipPossible: '', meridianFlipRequired: '', notes: ''},
		
		{mountType: 'AltazAltFlexRockers', priAxisAlign: 'Geographic', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Altaz with an additional flex rocker at 90 degrees for limited 3rd axis motion<br><a href="25/25 inch F2.6 Telescope.html" target="_blank">my 25 inch F2.6 telescope</a><br><br>'},
		{mountType: 'AltAltAz', priAxisAlign: 'Geographic', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Can take several forms; good at satellite tracking<br><a href="https://www.cloudynights.com/topic/52173-tracy-wilsons-3-axis-telescope-mount/" target="_blank">Tracy Wilson 3-axis telescope</a><br><a href="ThreeAxisMounts.html" target="_blank">some 3 axis ideas</a><br><br>'},

		{mountType: '<br><b>Omni-axis</b>:', priAxisAlign: '', canMoveToPriAxisPole: '', canMoveThruPriAxisPole: '', priAxisFullyRotates: '', meridianFlipPossible: '', meridianFlipRequired: '', notes: ''},
		
		{mountType: 'Ballscope', priAxisAlign: 'Geographic', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Lemay and Oltion have invented equatorial trackers for ballscopes<br><a href="ballscopes/ballscopes.html" target="_blank">my ballscope analysis</a><br><a href="http://www.jerryoltion.com/trackball.htm" target="_blank">Jerry Oltion tracking ballscope</a><br><a href="http://telescopelemay.com/language/en/20-inch-ball-scope/" target=_blank">Pierre Lemay 20 inch ballscope</a><br><br>'},
		{mountType: 'Holcombe/Sellers/et al', priAxisAlign: 'Geographic', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'yes', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Telescope and two legs form tripod<br><a href="HolcombeMount.html" target="_blank">the Holcombe mount</a><br><a href="6inchtravelscope.html" target="_blank">my 6 inch travelscope</a><br><br>'},
		{mountType: 'Hexapod', priAxisAlign: 'Geographic', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'yes', priAxisFullyRotates: 'no', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Six legged affair where the lengths of the legs are adjusted to point anywhere in the sky; field rotates<br><a href="https://en.wikipedia.org/wiki/Hexapod-Telescope" target="_blank">Hexapod-Telescope</a><br><br>'},

		{mountType: '<br><b>Equatorial</b>:', priAxisAlign: '', canMoveToPriAxisPole: '', canMoveThruPriAxisPole: '', priAxisFullyRotates: '', meridianFlipPossible: '', meridianFlipRequired: '', notes: ''},
		
		{mountType: 'CrossAxisEnglish', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'yes', priAxisFullyRotates: 'yes', meridianFlipPossible: 'yes', meridianFlipRequired: 'no', notes: 'Polar axis long and stable but requires counterweight, which can be moved up and down polar tube; not many transportable examples<br><a href="http://www.astronomyasylum.com/telescopemountstutorial.html" target="_blank">telescope mount tutorial</a><br><br>'},
		{mountType: 'EquatorialFork', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'yes', priAxisFullyRotates: 'yes', meridianFlipPossible: 'yes', meridianFlipRequired: 'no', notes: 'Versatile, popular<br><a href="10inch.html" target="_blank">my 10 inch fork mounted equatorial</a><br><a href="RobADob.html" target="_blank">Rob Adams 12 inch tilted Dob equatorial</a><br><br>'},
		{mountType: 'EquatorialSingleArmFork', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'yes', priAxisFullyRotates: 'yes', meridianFlipPossible: 'yes', meridianFlipRequired: 'no', notes: 'Closer access to tube with fork tine on opposite side; requires tine and tube to be balanced<br><a href="http://www.synrgistic.com/astro/telescopes.htm" target="_blank">Greg Babock single arm fork</a><br><br>'},
		{mountType: 'Equatorial(double)Yoke', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'no', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: 'no', meridianFlipRequired: 'no', notes: 'Yoke must be very long for tube to swing through upper polar end<br><a href="https://www.cloudynights.com/topic/512634-anyone-done-a-cradle-mount/" target="_blank">Cloudy Nights image</a><br><br>'},
		{mountType: 'GermanExtended', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'yes', priAxisFullyRotates: 'yes', meridianFlipPossible: 'yes', meridianFlipRequired: 'no', notes: 'Polar axis extended so that tube can swing underneath in place of meridian flip<br><br>'},
		{mountType: 'GermanMount', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: 'yes', meridianFlipRequired: 'yes' , notes: 'Historically popular mount<br><a href="http://www.astronomyasylum.com/telescopemountstutorial.html" target="_blank">telescope mount tutorial</a><br><br>'},
		{mountType: 'GermanCenterBalanced', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: 'yes', meridianFlipRequired: 'yes' , notes: 'Recent innovation where Dec axis rides between polar axis bearings and counterweight is placed outside<br><a href="https://tinyurl.com/y9wrpf3c" target=_blank">search german equatorial mount center balanced<br><br>'},
		{mountType: 'Horseshoe', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'no', meridianFlipPossible: 'no', meridianFlipRequired: 'no', notes: 'Think Palomar 200 inch telescope: no cantilevered loads; telescope can point to pole; low periodic error tracking when driving the horseshoe with a roller<br><a href="14inch.html" target="_blank">my 14 inch horseshoe</a><br><a href="8inchHorseshoe.html" target="_blank">my 8 inch horseshoe</a><br><br>'},
		{mountType: 'InvertedFork', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: 'no', meridianFlipRequired: 'no', notes: 'Popularized by Zeiss<br><a href="http://griffithobservatory.org/exhibits/zeiss_telescope.html" target="_blank">Griffith Observatory Zeiss telescope</a><br><br>'},
		{mountType: 'TorqueTube', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'yes', priAxisFullyRotates: 'yes', meridianFlipPossible: 'yes', meridianFlipRequired: 'no', notes: 'Boller and Chivens made a number of observatory class telescopes with ths mount design<br><a href="http://www.synrgistic.com/astro/telescopes.htm" target="_blank">Greg Babcock 10 inch torque tube</a><br><br>'},
		{mountType: 'SplitRing', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'yes', priAxisFullyRotates: 'no', meridianFlipPossible: 'no', meridianFlipRequired: 'no', notes: 'Cousin of Horseshoe<br><a href="https://tinyurl.com/yaqkw7za" target="_blank">search for split ring telescope mount</a><br><br>'},
		{mountType: 'Springfield', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'yes', priAxisFullyRotates: 'no', meridianFlipPossible: 'yes', meridianFlipRequired: 'yes' , notes: 'Stationary eyepiece; counterweight swings overhead<br><a href="https://tinyurl.com/yapyqnlh" target="_blank">search for Springfield telescope mount</a><br><br>'},

		{mountType: '<br><b>Stationary telescope</b>:', priAxisAlign: '', canMoveToPriAxisPole: '', canMoveThruPriAxisPole: '', priAxisFullyRotates: '', meridianFlipPossible: '', meridianFlipRequired: '', notes: ''},
		
		{mountType: 'Coelostat', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'no', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'no', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'One or two mirrors where one mirror is parallel to the polar axis<br><br>'},
		{mountType: 'Coude', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'yes', priAxisFullyRotates: 'no', meridianFlipPossible: 'yes', meridianFlipRequired: 'no', notes: 'Elbow telescope that keeps the image at a fixed position<br><br>'},
		{mountType: 'Heliostat', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'no', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Single feed mirror mounted equatorially restricted to solar observing<br><br>'},
		{mountType: 'PolarHeliostat', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'no', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Telescope situated along the polar axis<br><br>'},
		{mountType: 'PolarSiderostat', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'no', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Telescope situated along the polar axis<br><br>'},
		{mountType: 'Siderostat', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'no', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Single feed mirror mounted equatorially<br><br>'},
		{mountType: 'Uranostat', priAxisAlign: 'Celestial', canMoveToPriAxisPole: 'yes', canMoveThruPriAxisPole: 'no', priAxisFullyRotates: 'yes', meridianFlipPossible: '', meridianFlipRequired: '', notes: 'Single feed mirror mounted altazimuthly'}

	]
};
