MLB.spiderTypesJson = {
	'spiderTypes': [
		{spiderType: '4 vane', diffractionPattern: '4 spikes in a "+" shape', description: '4 vanes in a "+" shape; most popular design; commercially available', strength: 'easy to build and mount', weakness: 'large heavy diagonals can quiver because of weak torsional resistance', examples: '<a href="https://tinyurl.com/y92rymwu" target="_blank">4 vane search</a>'},
		{spiderType: '3 vane', diffractionPattern: '6 spikes in an hexagonal pattern', description: '3 vanes spaced at 120 degree angles', strength: 'slightly less diffraction than 4 vanes', weakness: '6 spikes vs 4 spikes for the 4 vane spider; susceptibility for large heavy diagonals to quiver because of weak torsional resistance', examples: '<a href="https://tinyurl.com/ydcyjrul" target="_blank">3 vane search</a>'},
		{spiderType: 'bar', diffractionPattern: 'single bright spike stretching away from stars like outstretched hands', description: 'a single thick bar stretching from one side of the tube to the other', strength: 'easy to manufacture and mount', weakness: 'greater overall diffraction', examples: '<a href="https://tinyurl.com/y7vlmzrt" target="_blank">Coulter telescope single bar spider</a>'},
		{spiderType: 'single stalk', diffractionPattern: 'single spike stretching away from stars like outstretched hands', description: 'a single stalk from edge of tube to diagonal holder', strength: 'easy to make', weakness: 'can bend', examples: '<a href="12 inch A frame Dob.JPG" target="_blank">12.5 inch F6 with single stalk spider</a>'},
		{spiderType: 'curved 3 vane spider', diffractionPattern: 'a smear of light around stars', description: '3 vane spider only with curved vanes', strength: 'when the vanes are highly curved, there is hardly any diffraction spikes', weakness: 'smeared light around stars', examples: '<a href="https://tinyurl.com/yczyqh6b" target="_blank">curved 3 vane search</a>'},
		{spiderType: 'curved single vane', diffractionPattern: 'a smear of light around stars', description: 'a single vane spider that is curved', strength: 'wehn the van is highly curved, there is hardly any dffraction spie', weakness: 'smeared light around stars', examples: '<a href="https://stellafane.org/tm/dob/ota/foc_diag_images/holder-finished.jpg" target="_blank">a curved single vane spider</a>'},
		{spiderType: 'V', diffractionPattern: 'two spikes at the angle of the V', description: 'shaped like the letter V', strength: 'robust and strong', weakness: 'typically more overall diffraction than a single stalk', examples: '<a href="http://www.bbastrodesigns.com/14%20inch%20guiding%20design.JPG" target="_blank">V shaped spider on a 14 inch with a shadow V spider for guiding</a>'},
		{spiderType: 'wire spider', diffractionPattern: 'essentially none', description: 'wires, typically 8 incount, used to suspect the diagonal and holder', strength: 'lack of diffraction', weakness: 'complex to build; needs jig to center diagonal holder while wiring', examples: '<a href="http://www.bbastrodesigns.com/25/wire%20spider.jpg" target="_blank">wire spider on a 25 inch</a>'},
		{spiderType: '', diffractionPattern: '', description: '', strength: '', weakness: '', examples: '<a href="" target="_blank"></a>'}
	]
};
