MLB.tubeTypesJson = {
	'tubeTypes': [
		{tubeType: 'Solid', numberOfTrusses: 'na', localSeeingIssues: 'Must cool down mirror; insulate metal tubes', engineeringNotes: 'Round tubes available in many materials; can be octagonal or hexagonal; may be heavy in larger sizes; keep round at the ends; can be thought of as a single hollow truss tube with internal optics', examples: '<a href="8 inch plastic tube.JPG" target="_blank">8 inch Dob</a><br><a href="10.5inchF2.7/10.5 inch finished 4.JPG" target="_blank">10 inch hexagonal</a>'},
		{tubeType: 'Bay', numberOfTrusses: 'na', localSeeingIssues: 'Exposed diagonal can dew', engineeringNotes: 'Can be cut from solid tube; can use wires', examples: '<a href="https://mcdonaldobservatory.org/sites/default/files/images/news/gallery/Tele_82.jpg" target="_blank">McDonald Observatory 82 inch</a><br><a href="https://upload.wikimedia.org/wikipedia/commons/b/be/Lanature1873_telescope_lassel.png" target="_blank">Lassell 48 inch</a>'},
		{tubeType: 'One truss', numberOfTrusses: '1', localSeeingIssues: 'Exposed diagonal can dew', engineeringNotes: 'Single truss must be quite stiff', examples: '<A href="http://www.stardazed.com/" target="_blank">Ross Sackett travelscopes</a><br><a href="http://www.litescope.net/litescope products.html" target=_blank">Cambridge LiteScope</a><br><a href="FoldingScopes/BobCox2.jpg" target="_blank">Bob Cox folding Cassegrain</a>'},
		{tubeType: 'A-frame', numberOfTrusses: '2', localSeeingIssues: 'Exposed diagonal can dew', engineeringNotes: 'Be careful of torque that twists the focuser board', examples: '<a href="http://www.bbastrodesigns.com/12 inch A frame Dob.JPG" target="_blank">12 inch A frame Dob</a>'},
		{tubeType: 'Two truss - one side', numberOfTrusses: '2', localSeeingIssues: 'Exposed diagonal can dew', engineeringNotes: 'Be careful of torque that twists the focuser board', examples: '<a href="https://stellafane.org/convention/2016/images/scopes/scope07a.jpg" target="_blank">Peter Pekurar 12 inch Hobbit telescope</a>'},
		{tubeType: 'Two truss, two sides', numberOfTrusses: '2', localSeeingIssues: 'Exposed diagonal can dew', engineeringNotes: 'Diagonal holder is typically a single strut from one truss tube to the other', examples: '<a href="ZipDob/ZipDobII/side.JPG" target="_blank">ZipDob J frame</a>'},
		{tubeType: 'Three straight truss', numberOfTrusses: '3', localSeeingIssues: 'Exposed diagonal can dew', engineeringNotes: 'See Albert Highes book', examples: '<a href="http://www.dobstuff.com/pictures.htm" target=_blank">DobStuff telescopes</a>'},
		{tubeType: 'Four straight truss', numberOfTrusses: '4', localSeeingIssues: 'Exposed diagonal can dew', engineeringNotes: 'Similar to three straight trusses', examples: '<A href="FoldingScopes/GregBabcockTravelScope.jpg" target="_blank">Greg Babcock travel scope</a><br><a href="https://www.cloudynights.com/uploads/monthly_07_2012/post-52067-14073902292189_thumb.jpg" target=_blank">Teleport collapsable telescope</a>'},
		{tubeType: 'Six truss', numberOfTrusses: '6', localSeeingIssues: 'Exposed diagonal can dew', engineeringNotes: 'Similar to 8 truss designs but need wider base to prevent tubes from intruding into light path', examples: '<a href="http://www.bbastrodesigns.com/TrilatForwardSideViewCat.jpg" target=_blank">20.5 inch TriDod</a>'},
		{tubeType: 'Eight truss', numberOfTrusses: '8', localSeeingIssues: 'Exposed diagonal can dew', engineeringNotes: 'Truss tube connectors are critical', examples: '<a href="20 inch v3.JPG" target="_blank">20.5 inch computerized altazimuth</a>'},
		{tubeType: 'String (conventional)', numberOfTrusses: '6', localSeeingIssues: 'Exposed diagonal can dew', engineeringNotes: 'Portland, Oregon is a hotbed of string telescopes', examples: '<a href="https://sites.google.com/view/astronomy-db/string-telescope-concepts" target=_blank">String scopes</a><br><a href="https://faculty.up.edu/lulay/KensTelescopePage.html" target=_blank">Ken Lulay\'s string scope</a>'},
		{tubeType: 'Tensegrity (string+rod)', numberOfTrusses: '6', localSeeingIssues: 'Exposed diagonal can dew', engineeringNotes: 'Invented by Don Peckham; amazingly strong design', examples: '<a href="https://sites.google.com/view/astronomy-db/dons-tensegrity-telescopes" target=_blank">Don Peckham Tensegrity telescopes</a>'}
	]
};
